/*
 * File: app/view/weekly/skills/NewForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.weekly.skills.NewForm', {
	extend: 'Ext.form.Panel',
	alias: 'widget.weeklyskillsnewform',

	requires: [
		'MySchool.view.common.QuarterSubjectComboBox',
		'MySchool.view.common.MonthComboBox',
		'Ext.form.FieldSet',
		'Ext.form.field.ComboBox',
		'Ext.form.field.Number',
		'Ext.form.field.Hidden',
		'Ext.button.Button'
	],

	draggable: true,
	floating: true,
	frame: true,
	itemId: 'weeklyskillsnewformpanel',
	width: 500,
	bodyPadding: 10,
	title: 'New Weekly Skills Form',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'fieldset',
					itemId: 'skillsfieldset',
					title: 'Skills Fields',
					items: [
						{
							xtype: 'textfield',
							anchor: '100%',
							itemId: 'skills-studentname',
							fieldLabel: 'Student User Name',
							name: 'studentUserName',
							readOnly: true,
							allowBlank: false
						},
						{
							xtype: 'commonquartersubjectcombobox',
							anchor: '100%'
						},
						{
							xtype: 'commonmonthcombobox',
							anchor: '100%'
						},
						{
							xtype: 'numberfield',
							anchor: '100%',
							itemId: 'skills-week_number',
							fieldLabel: 'Week Number',
							name: 'week_number',
							maxValue: 5,
							minValue: 1
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-remembering',
							fieldLabel: 'remembering',
							name: 'remembering',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-understanding',
							fieldLabel: 'understanding',
							name: 'understanding',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-applying',
							fieldLabel: 'applying',
							name: 'applying',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-analyzing',
							fieldLabel: 'analyzing',
							name: 'analyzing',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-evaluating',
							fieldLabel: 'evaluating',
							name: 'evaluating',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-creating',
							fieldLabel: 'creating',
							name: 'creating',
							value: 5
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-comments',
							fieldLabel: 'comments',
							name: 'comments',
							value: 'comments'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-subjectname',
							fieldLabel: 'subjectname',
							name: 'subjName'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-quarter',
							fieldLabel: 'quarter',
							name: 'qtrName'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-quarteryear',
							fieldLabel: 'year',
							name: 'qtrYear'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-studentid',
							fieldLabel: 'studentid',
							name: 'studentId'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-subjectid',
							fieldLabel: 'subjectId',
							name: 'subjId'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'skills-quarterid',
							fieldLabel: 'quarterid',
							name: 'qtrId'
						}
					]
				},
				{
					xtype: 'button',
					itemId: 'skillscancel',
					text: 'Canel'
				},
				{
					xtype: 'button',
					itemId: 'skillssubmit',
					text: 'Submit'
				}
			]
		});

		me.callParent(arguments);
	}

});