/*
 * File: app/model/bodiesofwork/BodiesOfWorkModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.bodiesofwork.BodiesOfWorkModel', {
	extend: 'Ext.data.Model',
	alias: 'model.bodiesofworkmodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id'
		},
		{
			name: 'subjId',
			type: 'int'
		},
		{
			name: 'qtrId',
			type: 'int'
		},
		{
			name: 'version',
			type: 'int'
		},
		{
			name: 'studentId',
			type: 'int'
		},
		{
			name: 'studentUserName',
			type: 'string'
		},
		{
			name: 'facultyUserName',
			type: 'string'
		},
		{
			name: 'subjName',
			type: 'string'
		},
		{
			name: 'qtrName',
			type: 'string'
		},
		{
			name: 'qtrYear',
			type: 'int'
		},
		{
			name: 'workName',
			type: 'string'
		},
		{
			name: 'description',
			type: 'string'
		},
		{
			name: 'what',
			type: 'string'
		},
		{
			name: 'objective',
			type: 'string'
		},
		{
			name: 'locked',
			type: 'boolean'
		},
		{
			name: 'whoUpdated',
			type: 'string'
		},
		{
			dateFormat: 'm/d/Y',
			name: 'lastUpdated',
			type: 'date'
		},
		{
			name: 'subjGradeLevel',
			type: 'int'
		},
		{
			name: 'subjCreditHours',
			type: 'int'
		}
	]
});