/*
 * File: app/model/monthly/EvaluationRatings.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.monthly.EvaluationRatings', {
	extend: 'Ext.data.Model',
	alias: 'model.monthlyevaluationratingsmodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id'
		},
		{
			name: 'month_number',
			type: 'int'
		},
		{
			name: 'levelOfDifficulty',
			type: 'int'
		},
		{
			name: 'criticalThinkingSkills',
			type: 'int'
		},
		{
			name: 'effectiveCorrectionActions',
			type: 'int'
		},
		{
			name: 'accuratelyIdCorrections',
			type: 'int'
		},
		{
			name: 'completingCourseObjectives',
			type: 'int'
		},
		{
			name: 'thoughtfulnessOfReflections',
			type: 'int'
		},
		{
			name: 'responsibilityOfProgress',
			type: 'int'
		},
		{
			name: 'workingEffectivelyWithAdvisor',
			type: 'int'
		},
		{
			name: 'comments',
			type: 'string'
		},
		{
			name: 'locked',
			type: 'boolean'
		},
		{
			dateFormat: 'm/d/Y',
			name: 'lastUpdated',
			type: 'date'
		},
		{
			name: 'whoUpdated',
			type: 'string'
		},
		{
			name: 'qtrName',
			type: 'string'
		},
		{
			name: 'qtrYear',
			type: 'int'
		},
		{
			name: 'qtrId'
		},
		{
			name: 'subjId'
		},
		{
			name: 'subjName',
			type: 'string'
		},
		{
			name: 'studentId'
		},
		{
			name: 'studentUserName',
			type: 'string'
		},
		{
			name: 'facultyUserName',
			type: 'string'
		},
		{
			name: 'version',
			type: 'int'
		},
		{
			name: 'monthlyevaluationId',
			type: 'int'
		}
	]
});