/*
 * File: app/model/common/QuarterSubjectModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.common.QuarterSubjectModel', {
	extend: 'Ext.data.Model',
	alias: 'model.commonquartersubjectmodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id',
			type: 'int'
		},
		{
			name: 'name',
			type: 'string'
		},
		{
			name: 'qtrId',
			type: 'int'
		},
		{
			name: 'qtrName',
			type: 'string'
		},
		{
			name: 'subjId',
			type: 'int'
		},
		{
			name: 'subjName',
			type: 'string'
		}
	]
});