/*
 * File: app/model/subject/SchoolsModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.subject.SchoolsModel', {
	extend: 'Ext.data.Model',
	alias: 'model.subjectschoolsmodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id'
		},
		{
			name: 'name'
		},
		{
			name: 'email'
		},
		{
			name: 'district'
		},
		{
			name: 'custodianOfRecords'
		},
		{
			name: 'custodianTitle'
		},
		{
			name: 'phone1'
		},
		{
			name: 'phone2'
		},
		{
			name: 'address1'
		},
		{
			name: 'address2'
		},
		{
			name: 'city'
		},
		{
			name: 'province'
		},
		{
			name: 'postalCode'
		},
		{
			name: 'country'
		},
		{
			name: 'comments'
		},
		{
			name: 'whoUpdated'
		},
		{
			name: 'createdDate'
		},
		{
			name: 'lastUpdated'
		}
	]
});