/*
 * File: app/store/subject/GradeTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.subject.GradeTypeStore', {
	extend: 'Ext.data.Store',

	requires: [
		'Ext.data.Field'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: true,
			storeId: 'subject.GradeTypeStore',
			data: [
				{
					name: 'Regular',
					value: '1'
				},
				{
					name: 'Pass/Fail',
					value: '2'
				}
			],
			fields: [
				{
					name: 'name',
					type: 'string'
				},
				{
					name: 'value',
					type: 'int'
				}
			]
		}, cfg)]);
	}
});