/*
 * File: app/store/subject/SchoolsStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.subject.SchoolsStore', {
	extend: 'Ext.data.Store',
	alias: 'store.subjectschoolsstore',

	requires: [
		'MySchool.model.subject.SchoolsModel',
		'Ext.data.proxy.Rest',
		'Ext.data.reader.Json'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: true,
			model: 'MySchool.model.subject.SchoolsModel',
			storeId: 'subject.SchoolsStore',
			proxy: {
				type: 'rest',
				url: 'schools/json',
				headers: {
					Accept: 'application/json'
				},
				reader: {
					type: 'json',
					root: 'data'
				}
			}
		}, cfg)]);
	}
});