/*
 * File: app/model/faculty/ByStudentModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.faculty.ByStudentModel', {
	extend: 'Ext.data.Model',
	alias: 'model.facultybystudentmodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id'
		},
		{
			name: 'facultybystudentId',
			type: 'int'
		},
		{
			name: 'firstName',
			type: 'string'
		},
		{
			name: 'middleName',
			type: 'string'
		},
		{
			name: 'lastName',
			type: 'string'
		},
		{
			name: 'address1',
			type: 'string'
		},
		{
			name: 'address2',
			type: 'string'
		},
		{
			name: 'city',
			type: 'string'
		},
		{
			name: 'country',
			type: 'string'
		},
		{
			name: 'province',
			type: 'string'
		},
		{
			name: 'postalCode',
			type: 'string'
		},
		{
			name: 'phone1',
			type: 'string'
		},
		{
			name: 'phone2',
			type: 'string'
		},
		{
			name: 'email',
			type: 'string'
		},
		{
			name: 'enabled',
			type: 'boolean'
		},
		{
			dateFormat: 'm/d/Y',
			name: 'lastUpdated',
			type: 'date'
		},
		{
			name: 'whoUpdated',
			type: 'string'
		},
		{
			name: 'qtrId',
			type: 'int'
		},
		{
			name: 'qtrName',
			type: 'string'
		},
		{
			name: 'qtrYear',
			type: 'int'
		},
		{
			name: 'studentId'
		},
		{
			name: 'studentUserName',
			type: 'string'
		},
		{
			name: 'subjId'
		},
		{
			name: 'subjName',
			type: 'string'
		},
		{
			name: 'schoolId',
			type: 'int'
		},
		{
			name: 'schoolName',
			type: 'string'
		},
		{
			name: 'version',
			type: 'int'
		},
		{
			name: 'facultyId'
		},
		{
			name: 'facultyUserName',
			type: 'string'
		}
	]
});