/*
 * File: app/view/monthly/summary/DetailsGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.monthly.summary.DetailsGridPanel', {
	extend: 'Ext.grid.Panel',
	alias: 'widget.monthlydetailsgridpanel',

	requires: [
		'Ext.grid.column.Number',
		'Ext.grid.View',
		'Ext.grid.column.CheckColumn',
		'Ext.form.field.Checkbox',
		'Ext.grid.column.Date'
	],

	itemId: 'monthlysummarygridpanel',
	minHeight: 150,
	autoScroll: true,
	title: '[student name]',
	forceFit: true,
	store: 'monthly.SummaryRatingsStore',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			columns: [
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'id',
					text: 'id'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'summaryId',
					text: 'summaryId'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'subjName',
					text: 'Subj Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'qtrName',
					text: 'Term'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'qtrYear',
					text: 'Year'
				},
				{
					xtype: 'numbercolumn',
					dataIndex: 'month_number',
					text: 'Month',
					format: '00'
				},
				{
					xtype: 'checkcolumn',
					hidden: true,
					dataIndex: 'locked',
					text: 'Locked?',
					editor: {
						xtype: 'checkboxfield'
					}
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'studentUserName',
					text: 'Student User Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'facultyUserName',
					text: 'Faculty User Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'whoUpdated',
					text: 'Who Updated'
				},
				{
					xtype: 'datecolumn',
					dataIndex: 'lastUpdated',
					text: 'Last Updated',
					format: 'm/d/Y'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'version',
					text: 'version',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'qtrId',
					text: 'termId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'subjId',
					text: 'subjId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'studentId',
					text: 'studentId',
					format: '000000'
				}
			],
			viewConfig: {
				id: 'monthlysummarygridview'
			}
		});

		me.callParent(arguments);
	}

});