/*
 * File: app/view/monthly/summary/NewSummaryFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.monthly.summary.NewSummaryFormPanel', {
	extend: 'Ext.form.Panel',
	alias: 'widget.monthlynewsummaryformpanel',

	requires: [
		'MySchool.view.common.QuarterSubjectComboBox',
		'MySchool.view.common.MonthComboBox',
		'Ext.form.FieldSet',
		'Ext.form.field.ComboBox',
		'Ext.form.field.Hidden',
		'Ext.button.Button'
	],

	draggable: true,
	floating: true,
	frame: true,
	itemId: 'monthlynewsummaryformpanel',
	width: 500,
	bodyPadding: 10,
	title: 'New Monthly Summary Form',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'fieldset',
					itemId: 'monthlysummaryfieldset',
					title: 'Monthly Summary Fields',
					items: [
						{
							xtype: 'textfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-studentname',
							fieldLabel: 'studentname',
							name: 'studentname',
							readOnly: true
						},
						{
							xtype: 'commonquartersubjectcombobox',
							anchor: '100%'
						},
						{
							xtype: 'commonmonthcombobox',
							anchor: '100%'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-feelings',
							fieldLabel: 'feelings',
							name: 'feelings',
							value: 'feelings'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-reflections',
							fieldLabel: 'reflections',
							name: 'reflections',
							value: 'reflections'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-patternsofcorrections',
							fieldLabel: 'patterns of correctons',
							name: 'patternsofcorrections',
							value: 'patterns of corrections'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-effectivenessofactions',
							fieldLabel: 'effectivenes of actions',
							name: 'effectivenessofactions',
							value: 'effectiveness of actions'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-actionresults',
							fieldLabel: 'action results',
							name: 'actionresults',
							value: 'action results'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-realizations',
							fieldLabel: 'realizations',
							name: 'realizations',
							value: 'realizations'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-plannedchanges',
							fieldLabel: 'planned changes',
							name: 'plannedchanges',
							value: 'planned changes'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-comments',
							fieldLabel: 'comments',
							name: 'comments',
							value: 'comments'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-subjectid',
							fieldLabel: 'subjectId',
							name: 'subjectId'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-quarterid',
							fieldLabel: 'quarterid',
							name: 'quarterId'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-subjectname',
							fieldLabel: 'subjectname',
							name: 'subjectname'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-studentid',
							fieldLabel: 'studentid',
							name: 'studentId'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-subject',
							fieldLabel: 'subject',
							name: 'subject'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-quarter',
							fieldLabel: 'quarter',
							name: 'quarter'
						},
						{
							xtype: 'hiddenfield',
							anchor: '100%',
							itemId: 'newmonthlysummary-year',
							fieldLabel: 'year',
							name: 'year'
						}
					]
				},
				{
					xtype: 'button',
					itemId: 'newmonthlysummarycanel',
					text: 'Canel'
				},
				{
					xtype: 'button',
					itemId: 'newmonthlysummarysubmit',
					text: 'Submit'
				}
			]
		});

		me.callParent(arguments);
	}

});