/*
 * File: app/model/daily/DailyModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.daily.DailyModel', {
	extend: 'Ext.data.Model',
	alias: 'model.dailymodel',

	requires: [
		'Ext.data.Field'
	],

	fields: [
		{
			name: 'id'
		},
		{
			name: 'qtrName',
			type: 'string'
		},
		{
			name: 'daily_year',
			type: 'int'
		},
		{
			name: 'daily_month',
			type: 'int'
		},
		{
			name: 'daily_day',
			type: 'int'
		},
		{
			name: 'daily_hours',
			type: 'float'
		},
		{
			name: 'resourcesUsed',
			type: 'string'
		},
		{
			name: 'studyDetails',
			type: 'string'
		},
		{
			name: 'evaluation',
			type: 'string'
		},
		{
			name: 'correction',
			type: 'string'
		},
		{
			name: 'dailyAction',
			type: 'string'
		},
		{
			name: 'comments',
			type: 'string'
		},
		{
			name: 'locked',
			type: 'boolean'
		},
		{
			name: 'whoUpdated',
			type: 'string'
		},
		{
			dateFormat: 'm/d/Y',
			name: 'lastUpdated',
			type: 'date'
		},
		{
			name: 'subjName',
			type: 'string'
		},
		{
			name: 'subjId',
			type: 'int'
		},
		{
			name: 'studentUserName',
			type: 'string'
		},
		{
			name: 'facultyUserName',
			type: 'string'
		},
		{
			name: 'studentId',
			type: 'int'
		},
		{
			name: 'qtrId',
			type: 'int'
		},
		{
			name: 'dailyId',
			type: 'int'
		},
		{
			name: 'version',
			type: 'int'
		}
	]
});