/*
 * File: app/store/guardian/GuardianTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.guardian.GuardianTypeStore', {
	extend: 'Ext.data.Store',
	alias: 'store.guardiantypestore',

	requires: [
		'MySchool.model.guardian.GuardianTypeModel',
		'Ext.data.Field'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: true,
			model: 'MySchool.model.guardian.GuardianTypeModel',
			storeId: 'guardian.GuardianTypeStore',
			data: [
				
			],
			fields: [
				{
					name: 'id',
					type: 'int'
				},
				{
					name: 'name',
					type: 'string'
				}
			]
		}, cfg)]);
	},

	myLoad: function() {
		this.removeAll();

		this.add( { name: "Father", id: 0});
		this.add( { name: "Mother", id: 1});
		this.add( { name: "Legal", id: 2});


	}

});