/*
 * File: app/view/student/NewForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.student.NewForm', {
	extend: 'Ext.form.Panel',
	alias: 'widget.studentnewform',

	requires: [
		'MySchool.view.subject.FacultyNamesComboBox',
		'Ext.form.FieldSet',
		'Ext.form.field.ComboBox',
		'Ext.button.Button'
	],

	draggable: true,
	floating: true,
	frame: true,
	itemId: 'studentnewform',
	width: 500,
	bodyPadding: 10,
	title: 'New Student Form',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'fieldset',
					itemId: 'studentnewformfieldset',
					title: 'Evaluations Fields',
					items: [
						{
							xtype: 'subjectfacultynamescombobox'
						}
					]
				},
				{
					xtype: 'button',
					itemId: 'studentcancel',
					text: 'Canel'
				},
				{
					xtype: 'button',
					itemId: 'studentsubmit',
					text: 'Submit'
				}
			]
		});

		me.callParent(arguments);
	}

});