/*
 * File: app/view/student/ProfileGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.student.ProfileGridPanel', {
	extend: 'Ext.grid.Panel',
	alias: 'widget.studentprofilegridpanel',

	requires: [
		'Ext.grid.column.Number',
		'Ext.form.field.Text',
		'Ext.grid.column.CheckColumn',
		'Ext.grid.column.Date',
		'Ext.grid.View',
		'Ext.grid.plugin.CellEditing'
	],

	itemId: 'studentprofilegridpanel',
	maxHeight: 200,
	minHeight: 200,
	autoScroll: true,
	title: '[faculty name]Students',
	columnLines: false,
	forceFit: true,
	store: 'student.StudentProfileStore',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			columns: [
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'studentId',
					text: 'studentId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'studentprofileviewId',
					text: 'studentprofileviewId',
					format: '000000'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'userName',
					text: 'Student User Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'middleName',
					text: 'Middle Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'firstName',
					text: 'First Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'lastName',
					text: 'Last Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'facultyEmail',
					text: 'Faculty Email'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'guardianUserName',
					text: 'Guardian User Name',
					editor: {
						xtype: 'textfield',
						allowBlank: false,
						allowOnlyWhitespace: false
					}
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'guardianEmail',
					text: 'Guardian Email'
				},
				{
					xtype: 'checkcolumn',
					hidden: true,
					itemId: 'studentprofilegridenabledcolumn',
					dataIndex: 'enabled',
					text: 'Enabled?'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'dob',
					text: 'dob'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'lastUpdated',
					text: 'Last Updated'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'whoUpdated',
					text: 'Who Updated'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'version',
					text: 'version',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'facultyId',
					text: 'facultyId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'guardianId',
					text: 'guardianId',
					format: '000000'
				}
			],
			plugins: [
				Ext.create('Ext.grid.plugin.CellEditing', {

				})
			]
		});

		me.callParent(arguments);
	}

});