/*
 * File: app/view/student/TranscriptDialog.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.student.TranscriptDialog', {
	extend: 'Ext.window.Window',

	requires: [
		'Ext.form.Panel',
		'Ext.form.FieldSet',
		'Ext.form.field.ComboBox',
		'Ext.button.Button'
	],

	height: 180,
	itemId: 'studenttranscriptdialog',
	width: 406,
	title: 'Create Student Transcript',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'form',
					dock: 'top',
					height: 131,
					itemId: 'studenttranscriptform',
					width: 390,
					bodyPadding: 10,
					dockedItems: [
						{
							xtype: 'fieldset',
							dock: 'top',
							height: 81,
							itemId: 'studenttranscriptformfieldset',
							padding: 5,
							items: [
								{
									xtype: 'combobox',
									anchor: '100%',
									itemId: 'studenttranscriptform_schoolname',
									fieldLabel: 'School Name',
									name: 'schoolname',
									emptyText: 'Select one.',
									displayField: 'name',
									forceSelection: true,
									store: 'subject.SchoolsStore',
									valueField: 'name'
								},
								{
									xtype: 'combobox',
									anchor: '100%',
									itemId: 'studenttranscriptform_studentname',
									fieldLabel: 'Student User Name',
									name: 'userName',
									emptyText: 'Select one.',
									displayField: 'userName',
									forceSelection: true,
									store: 'student.StudentStore',
									valueField: 'userName'
								}
							]
						}
					],
					items: [
						{
							xtype: 'button',
							itemId: 'studenttranscriptcancel',
							text: 'Cancel'
						},
						{
							xtype: 'button',
							itemId: 'studenttranscriptsubmit',
							text: 'Submit'
						}
					]
				}
			]
		});

		me.callParent(arguments);
	}

});