/*
 * File: app/store/bodiesofwork/MyJsonStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.bodiesofwork.MyJsonStore', {
	extend: 'Ext.data.Store',
	alias: 'store.bodiesofworkjsonstore',

	requires: [
		'MySchool.model.bodiesofwork.BodiesOfWorkModel',
		'Ext.data.proxy.Rest',
		'Ext.data.reader.Json'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: false,
			model: 'MySchool.model.bodiesofwork.BodiesOfWorkModel',
			storeId: 'bodiesofwork.MyJsonStore',
			proxy: {
				type: 'rest',
				url: 'bodyofworkviews',
				headers: {
					Accept: 'application/json'
				},
				reader: {
					type: 'json',
					root: 'data'
				}
			},
			listeners: {
				write: {
					fn: me.onJsonstoreWrite,
					scope: me
				},
				load: {
					fn: me.onJsonstoreLoad,
					scope: me
				}
			}
		}, cfg)]);
	},

	onJsonstoreWrite: function(store, operation, eOpts) {
		window.console.log( "BodiesOfWorkStore reload...");
		store.reload();
	},

	onJsonstoreLoad: function(store, records, successful, eOpts) {
		//debugger;
		console.log( "bodiesofwork.MyJsonStore(): load event called...");
	}

});