/*
 * File: app/store/bodiesofwork/MyJsonStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.bodiesofwork.MyJsonStore', {
	extend: 'Ext.data.Store',
	alias: 'store.bodiesofworkjsonstore',

	requires: [
		'MySchool.model.bodiesofwork.BodiesOfWorkModel',
		'Ext.data.proxy.Rest',
		'Ext.data.reader.Json'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: false,
			model: 'MySchool.model.bodiesofwork.BodiesOfWorkModel',
			storeId: 'bodiesofwork.MyJsonStore',
			proxy: {
				type: 'rest',
				url: 'bodyofworkviews/json',
				headers: {
					Accept: 'application/json'
				},
				reader: {
					type: 'json',
					root: 'data'
				},
				listeners: {
					exception: {
						fn: me.onRestException,
						scope: me
					}
				}
			},
			listeners: {
				write: {
					fn: me.onJsonstoreWrite,
					scope: me
				},
				load: {
					fn: me.onJsonstoreLoad,
					scope: me
				},
				add: {
					fn: me.onJsonstoreAdd,
					scope: me
				}
			}
		}, cfg)]);
	},

	onRestException: function(proxy, response, operation, eOpts) {
		//debugger;
		var smsg = response.request.options.method + '<br>' + response.request.options.action + '<br>' + response.responseText + '<br>' + response.status + '<br>' + response.statusText + '<br>' + operation.params.data;
		//Ext.MessageBox.show({
		//    title: 'REMOTE EXCEPTION',
		//    msg: smsg,
		//    icon: Ext.MessageBox.ERROR,
		//    buttons: Ext.Msg.OK,
		//    resizeable: true
		//});
		window.console.log( smsg );
		if( this.getCount() > 0 )
		{
		    this.reload();
		}
	},

	onJsonstoreWrite: function(store, operation, eOpts) {
		debugger;
		window.console.log( "BodiesOfWorkStore reload...");
		store.reload();
	},

	onJsonstoreLoad: function(store, records, successful, eOpts) {
		//debugger;
		console.log( "bodiesofwork.MyJsonStore(): load event called...");
	},

	onJsonstoreAdd: function(store, records, index, eOpts) {
		debugger;
		window.console.log( "BodiesOfWorkStore add...");
	}

});