/*
 * File: app/view/subject/SubjectsPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.subject.SubjectsPanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.subjectspanel',

	requires: [
		'MySchool.view.subject.SubjectsGridPanel',
		'MySchool.view.subject.SubjectsForm',
		'MySchool.view.subject.SubjectRefreshTool',
		'MySchool.view.subject.SubjectSearchTool',
		'MySchool.view.subject.SubjectNewTool',
		'MySchool.view.subject.SubjectSaveTool',
		'MySchool.view.subject.SubjectDeleteTool',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	id: 'subjectspanel',
	title: 'Subjects By Student',

	layout: {
		type: 'hbox',
		align: 'stretch'
	},

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'subjectsgridpanel',
					flex: 2
				},
				{
					xtype: 'subjectsform',
					flex: 1
				}
			],
			tools: [
				{
					xtype: 'subjectrefreshtool'
				},
				{
					xtype: 'subjectsearchtool',
					disabled: true
				},
				{
					xtype: 'subjectnewtool'
				},
				{
					xtype: 'subjectsavetool'
				},
				{
					xtype: 'subjectdeletetool'
				}
			]
		});

		me.callParent(arguments);
	}

});