/*
 * File: app/view/faculty/OnlyFacultyProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.faculty.OnlyFacultyProfilePanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.facultyonlyfacultyprofilepanel',

	requires: [
		'MySchool.view.faculty.ProfileGridFacultyOnlyPanel',
		'MySchool.view.faculty.FacultyOnlyProfileForm',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	itemId: 'facultyonlyprofilepanel',
	layout: 'fit',
	title: 'Faculty Profiles Details',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'facultyprofilegridfacultyonlypanel',
					dock: 'top'
				},
				{
					xtype: 'facultyfacultyonlyprofileform',
					dock: 'bottom'
				}
			],
			tools: [
				{
					xtype: 'tool',
					itemId: 'onlyfacultyrefreshtool',
					type: 'refresh'
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultysearchtool',
					type: 'search',
					listeners: {
						click: {
							fn: me.onOnlyfacultysearchtoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultynewtool',
					type: 'plus'
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultysavetool',
					type: 'save',
					listeners: {
						click: {
							fn: me.onOnlyfacultysavetoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultydeletetool',
					type: 'minus',
					listeners: {
						click: {
							fn: me.onOnlyfacultydeletetoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultylocktool',
					type: 'pin',
					listeners: {
						click: {
							fn: me.onOnlyfacultylocktoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyfacultylpasswordtool',
					type: 'gear'
				}
			]
		});

		me.callParent(arguments);
	},

	onOnlyfacultysearchtoolClick: function(tool, e, eOpts) {

	},

	onOnlyfacultysavetoolClick: function(tool, e, eOpts) {

	},

	onOnlyfacultydeletetoolClick: function(tool, e, eOpts) {

	},

	onOnlyfacultylocktoolClick: function(tool, e, eOpts) {

	}

});