/*
 * File: app/view/faculty/ProfileGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.faculty.ProfileGridPanel', {
	extend: 'Ext.grid.Panel',
	alias: 'widget.facultyprofilegridpanel',

	requires: [
		'Ext.grid.column.Number',
		'Ext.grid.column.CheckColumn',
		'Ext.grid.column.Date',
		'Ext.grid.View'
	],

	itemId: 'facultyprofilesbystudentgridpanel',
	maxHeight: 200,
	minHeight: 200,
	autoScroll: true,
	title: 'Faculty',
	forceFit: true,
	store: 'faculty.ByStudentStore',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			columns: [
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'id',
					text: 'id',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'facultybystudentId',
					text: 'faultybystudentId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'studentId',
					text: 'studentId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'subjId',
					text: 'subjId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'qtrId',
					text: 'qtrId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'facultyId',
					text: 'facultyId',
					format: '000000'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'facultyUserName',
					text: 'facultyUserName'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'subjName',
					text: 'subjName'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'studentUserName',
					text: 'studentUserName'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'qtrName',
					text: 'qtrName'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'qtrYear',
					text: 'qtrYear'
				},
				{
					xtype: 'checkcolumn',
					hidden: true,
					itemId: 'facultyprofilegridpanelenabled',
					dataIndex: 'enabled',
					text: 'Enabled?'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'version',
					text: 'version',
					format: '000000'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'whoUpdated',
					text: 'whoUpdated'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'lastUpdated',
					text: 'lastUpdated'
				}
			]
		});

		me.callParent(arguments);
	}

});