/*
 * File: app/view/faculty/ProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.faculty.ProfilePanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.facultyprofilepanel',

	requires: [
		'MySchool.view.faculty.ProfileGridPanel',
		'MySchool.view.faculty.ProfileForm',
		'MySchool.view.faculty.RefreshTool',
		'MySchool.view.faculty.SearchTool',
		'MySchool.view.faculty.NewTool',
		'MySchool.view.faculty.SaveTool',
		'MySchool.view.faculty.DeleteTool',
		'MySchool.view.faculty.LockTool',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	itemId: 'facultyprofilesbystudentdetailspanel',
	layout: 'fit',
	title: 'Faculty Profiles Details',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'facultyprofilegridpanel',
					dock: 'top'
				},
				{
					xtype: 'facultyprofileform',
					dock: 'bottom'
				}
			],
			tools: [
				{
					xtype: 'facultyrefreshtool'
				},
				{
					xtype: 'facultysearchtool',
					disabled: true
				},
				{
					xtype: 'facultynewtool'
				},
				{
					xtype: 'facultysavetool'
				},
				{
					xtype: 'facultydeletetool'
				},
				{
					xtype: 'facultylocktool'
				}
			]
		});

		me.callParent(arguments);
	}

});