/*
 * File: app/view/guardian/NewDialog.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.guardian.NewDialog', {
	extend: 'Ext.window.Window',

	requires: [
		'MySchool.view.guardian.GuardianTypesComboBox',
		'Ext.form.Panel',
		'Ext.form.FieldSet',
		'Ext.form.field.ComboBox',
		'Ext.form.field.Date',
		'Ext.button.Button'
	],

	height: 597,
	itemId: 'guardiannewdialog',
	width: 390,
	title: 'New Guardian',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'form',
					dock: 'top',
					height: 557,
					itemId: 'gaurdiannewform',
					width: 390,
					bodyPadding: 10,
					dockedItems: [
						{
							xtype: 'fieldset',
							dock: 'top',
							height: 497,
							itemId: 'guardiannewformfieldset',
							padding: 5,
							items: [
								{
									xtype: 'combobox',
									anchor: '100%',
									itemId: 'guardiannewform_studentname',
									fieldLabel: 'Student User Name',
									name: 'studentusername',
									displayField: 'userName',
									forceSelection: true,
									store: 'student.StudentStore',
									valueField: 'userName'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_username',
									fieldLabel: 'User Name',
									name: 'username',
									listeners: {
										boxready: {
											fn: me.onGuardiannewform_usernameBoxReady,
											scope: me
										}
									}
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_firstname',
									fieldLabel: 'First Name',
									name: 'firstname'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_middlename',
									fieldLabel: 'Middle',
									name: 'middlename'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_lastname',
									fieldLabel: 'Last Name',
									name: 'lastname'
								},
								{
									xtype: 'guardiantypescombobox',
									anchor: '100%'
								},
								{
									xtype: 'datefield',
									anchor: '100%',
									itemId: 'guardiannewform_dob',
									fieldLabel: 'DOB',
									name: 'dob'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_phone1',
									fieldLabel: 'Phone1',
									name: 'phone1'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_phone2',
									fieldLabel: 'Phone2',
									name: 'phone2'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_address1',
									fieldLabel: 'Address1',
									name: 'address1'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_address2',
									fieldLabel: 'Address2',
									name: 'address2'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_city',
									fieldLabel: 'City',
									name: 'city'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_state',
									fieldLabel: 'State/Province',
									name: 'state'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_postalcode',
									fieldLabel: 'Postal Code',
									name: 'postalcode'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_country',
									fieldLabel: 'Country',
									name: 'country'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'guardiannewform_email',
									fieldLabel: 'Email',
									name: 'email'
								}
							]
						}
					],
					items: [
						{
							xtype: 'button',
							itemId: 'guardiancancel',
							text: 'Cancel'
						},
						{
							xtype: 'button',
							itemId: 'guardiansubmit',
							text: 'Submit'
						}
					]
				}
			]
		});

		me.callParent(arguments);
	},

	onGuardiannewform_usernameBoxReady: function(component, width, height, eOpts) {
		component.focus(false, 200);
	}

});