/*
 * File: app/view/bodiesofwork/SearchTool.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.bodiesofwork.SearchTool', {
	extend: 'Ext.panel.Tool',
	alias: 'widget.bodiesofworksearchtool',

	itemId: 'toolsearchbodiesofwork',
	tooltip: 'Search',
	type: 'search',

	initComponent: function() {
		var me = this;

		me.callParent(arguments);
	}

});