/*
 * File: app/view/school/ProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.school.ProfilePanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.schoolprofilepanel',

	requires: [
		'MySchool.view.school.ProfileGridPanel',
		'MySchool.view.school.ProfileForm',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	itemId: 'schoolprofiledetailspanel',
	layout: 'fit',
	title: 'School Profiles Details',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'schoolprofilegridpanel',
					dock: 'top'
				},
				{
					xtype: 'schoolprofileform',
					dock: 'bottom'
				}
			],
			tools: [
				{
					xtype: 'tool',
					itemId: 'schoolrefreshtool',
					tooltip: 'Refresh',
					type: 'refresh'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'schoolsearchtool',
					tooltip: 'Search',
					type: 'search'
				},
				{
					xtype: 'tool',
					itemId: 'schoolnewtool',
					tooltip: 'Search',
					type: 'plus'
				},
				{
					xtype: 'tool',
					itemId: 'schoolsavetool',
					tooltip: 'Search',
					type: 'save'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'schooldeletetool',
					tooltip: 'Search',
					type: 'minus'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'schoollocktool',
					tooltip: 'Search',
					type: 'pin'
				}
			]
		});

		me.callParent(arguments);
	}

});