/*
 * File: app/view/admin/AdminProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.admin.AdminProfilePanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.adminadminprofilepanel',

	requires: [
		'MySchool.view.admin.ProfileGridAdminOnlyPanel',
		'MySchool.view.admin.AdminOnlyProfileForm',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	itemId: 'adminonlyprofilepanel',
	layout: 'fit',
	title: 'School Admin Profile Details',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'adminprofilegridadminonlypanel',
					dock: 'top'
				}
			],
			items: [
				{
					xtype: 'adminadminonlyprofileform'
				}
			],
			tools: [
				{
					xtype: 'tool',
					itemId: 'onlyadminrefreshtool',
					type: 'refresh'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadminsearchtool',
					type: 'search'
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminnewtool',
					type: 'plus'
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminsavetool',
					type: 'save'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadmindeletetool',
					type: 'minus'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadminlocktool',
					type: 'pin'
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminpasswordtool',
					type: 'gear'
				}
			]
		});

		me.callParent(arguments);
	}

});