/*
 * File: app/view/admin/AdminProfilePanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.admin.AdminProfilePanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.adminadminprofilepanel',

	requires: [
		'MySchool.view.admin.ProfileGridAdminOnlyPanel',
		'MySchool.view.admin.AdminProfileForm',
		'Ext.grid.Panel',
		'Ext.form.Panel',
		'Ext.panel.Tool'
	],

	itemId: 'adminprofilepanel',
	layout: 'fit',
	title: 'School Admin Profile Details',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'adminprofilegridadminonlypanel',
					dock: 'top'
				}
			],
			items: [
				{
					xtype: 'adminadminprofileform'
				}
			],
			tools: [
				{
					xtype: 'tool',
					itemId: 'onlyadminrefreshtool',
					tooltip: 'Refresh',
					type: 'refresh'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadminsearchtool',
					tooltip: 'Search',
					type: 'search',
					listeners: {
						click: {
							fn: me.onOnlyadminsearchtoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminnewtool',
					tooltip: 'New',
					type: 'plus'
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminsavetool',
					tooltip: 'Save',
					type: 'save'
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadmindeletetool',
					tooltip: 'Delete',
					type: 'minus',
					listeners: {
						click: {
							fn: me.onOnlyadmindeletetoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					disabled: true,
					itemId: 'onlyadminlocktool',
					tooltip: 'Lock',
					type: 'pin',
					listeners: {
						click: {
							fn: me.onOnlyadminlocktoolClick,
							scope: me
						}
					}
				},
				{
					xtype: 'tool',
					itemId: 'onlyadminpasswordtool',
					tooltip: 'Password',
					type: 'gear'
				}
			]
		});

		me.callParent(arguments);
	},

	onOnlyadminsearchtoolClick: function(tool, e, eOpts) {

	},

	onOnlyadmindeletetoolClick: function(tool, e, eOpts) {

	},

	onOnlyadminlocktoolClick: function(tool, e, eOpts) {

	}

});