/*
 * File: app/view/admin/NewDialog.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.admin.NewDialog', {
	extend: 'Ext.window.Window',

	requires: [
		'Ext.form.Panel',
		'Ext.form.FieldSet',
		'Ext.form.field.Date',
		'Ext.button.Button'
	],

	height: 548,
	itemId: 'adminnewdialog',
	width: 390,
	title: 'New School Admin',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			dockedItems: [
				{
					xtype: 'form',
					dock: 'top',
					frame: true,
					height: 508,
					itemId: 'adminnewform',
					width: 381,
					bodyPadding: 10,
					dockedItems: [
						{
							xtype: 'fieldset',
							dock: 'top',
							height: 445,
							itemId: 'adminnewformfieldset',
							padding: 5,
							items: [
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_firstname',
									fieldLabel: 'First Name',
									name: 'firstname',
									listeners: {
										boxready: {
											fn: me.onNewform_firstnameBoxReady,
											scope: me
										}
									}
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_middlename',
									fieldLabel: 'Middle',
									name: 'middlename'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_lastname',
									fieldLabel: 'Last Name',
									name: 'lastname'
								},
								{
									xtype: 'datefield',
									anchor: '100%',
									itemId: 'newform_dob',
									fieldLabel: 'DOB',
									name: 'dob'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_phone1',
									fieldLabel: 'Phone1',
									name: 'phone1'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_phone2',
									fieldLabel: 'Phone2',
									name: 'phone2'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_address1',
									fieldLabel: 'Address1',
									name: 'address1'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_address2',
									fieldLabel: 'Address2',
									name: 'address2'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_city',
									fieldLabel: 'City',
									name: 'city'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_state',
									fieldLabel: 'State/Province',
									name: 'state'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_postalcode',
									fieldLabel: 'Postal Code',
									name: 'postalcode'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_country',
									fieldLabel: 'Country',
									name: 'country'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_email',
									fieldLabel: 'Email',
									name: 'email'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_username',
									fieldLabel: 'User Name',
									name: 'username'
								},
								{
									xtype: 'textfield',
									anchor: '100%',
									itemId: 'newform_password',
									fieldLabel: 'Password',
									name: 'password'
								}
							]
						}
					],
					items: [
						{
							xtype: 'button',
							itemId: 'admincancel',
							text: 'Cancel'
						},
						{
							xtype: 'button',
							itemId: 'adminsubmit',
							text: 'Submit'
						}
					]
				}
			]
		});

		me.callParent(arguments);
	},

	onNewform_firstnameBoxReady: function(component, width, height, eOpts) {
		component.focus(false, 200);
	}

});