/*
 * File: app/view/admin/ProfileGridAdminOnlyPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.admin.ProfileGridAdminOnlyPanel', {
	extend: 'Ext.grid.Panel',
	alias: 'widget.adminprofilegridadminonlypanel',

	requires: [
		'Ext.grid.column.Number',
		'Ext.form.field.ComboBox',
		'Ext.grid.column.CheckColumn',
		'Ext.grid.column.Date',
		'Ext.grid.View',
		'Ext.grid.plugin.CellEditing'
	],

	itemId: 'admingridpanel',
	maxHeight: 200,
	minHeight: 200,
	autoScroll: true,
	title: 'School Admins',
	forceFit: true,
	store: 'admin.AdminProfileStore',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			columns: [
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'id',
					text: 'id',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'adminId',
					text: 'adminId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'adminviewId',
					text: 'adminviewId',
					format: '000000'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'schoolId',
					text: 'schoolId',
					format: '000000'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'userName',
					text: 'Admin User Name',
					editor: {
						xtype: 'combobox',
						name: 'username',
						displayField: 'userName',
						store: 'admin.AdminStore',
						valueField: 'userName'
					}
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'schoolName',
					text: 'School Name'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'firstName',
					text: 'First Name'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'middleName',
					text: 'Middle Name'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'lastName',
					text: 'Last Name'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'email',
					text: 'Admin Email'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'phone1',
					text: 'phone1'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'phone2',
					text: 'phone2'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'address1',
					text: 'address1'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'address2',
					text: 'address2'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'city',
					text: 'city'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'province',
					text: 'province'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'postalCode',
					text: 'postalCode'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'country',
					text: 'country'
				},
				{
					xtype: 'checkcolumn',
					hidden: true,
					itemId: 'adminprofilegridpanelenabled',
					dataIndex: 'enabled',
					text: 'Enabled?'
				},
				{
					xtype: 'numbercolumn',
					hidden: true,
					dataIndex: 'version',
					text: 'version',
					format: '000000'
				},
				{
					xtype: 'gridcolumn',
					hidden: true,
					dataIndex: 'whoUpdated',
					text: 'Who Updated'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'lastUpdated',
					text: 'Last Updated'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'createdDate',
					text: 'Created Date'
				},
				{
					xtype: 'datecolumn',
					hidden: true,
					dataIndex: 'dob',
					text: 'dob'
				}
			],
			plugins: [
				Ext.create('Ext.grid.plugin.CellEditing', {

				})
			]
		});

		me.callParent(arguments);
	}

});